val it = () : unit
exception exc_test
val x = 1 : int
